require("raster")
require("rworldmap")
require("rworldxtra")

png(filename = "~/Documents/Occupancy/CostaRica-SRTM-HGT.png", width = 1024, height = 768)
par(mar = c(5,5,5,5)+0.1)
plot(x = 0, y = 0, xlim = c(-86,-82), ylim = c(8,11), xlab = "Longitude", ylab = "Latitude", main = "Elevation in Costa Rica", type = "n")

elevation <- raster("~/Downloads/HGT/N08W083.hgt")
plot(elevation, add = TRUE)
elevation <- raster("~/Downloads/HGT/N08W084.hgt")
plot(elevation, add = TRUE, legend = FALSE)
elevation <- raster("~/Downloads/HGT/N09W083.hgt")
plot(elevation, add = TRUE, legend = FALSE)
elevation <- raster("~/Downloads/HGT/N09W084.hgt")
plot(elevation, add = TRUE, legend = FALSE)
elevation <- raster("~/Downloads/HGT/N09W085.hgt")
plot(elevation, add = TRUE, legend = FALSE)
elevation <- raster("~/Downloads/HGT/N09W086.hgt")
plot(elevation, add = TRUE, legend = FALSE)
elevation <- raster("~/Downloads/HGT/N10W084.hgt")
plot(elevation, add = TRUE, legend = FALSE)
elevation <- raster("~/Downloads/HGT/N10W085.hgt")
plot(elevation, add = TRUE, legend = FALSE)
elevation <- raster("~/Downloads/HGT/N10W086.hgt")
plot(elevation, add = TRUE, legend = FALSE)
newmap <- getMap(resolution = "high")

plot(newmap, add = TRUE, xlim = c(-86,-82), ylim = c(8,11))
par(bg = "white", mar = c(5,4,4,2)+0.1)
dev.off()
